bilimli/apps/accounts/urls.py
from django.urls import path

from .views import register, edit, profile
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('signup/', register, name='register'),
    path('login/', auth_views.LoginView
         .as_view(template_name='register/login.html'), name='login'),
    path('edit/',edit, name='edit'),
    path('profile/<username>', profile, name='profile')
]

bilimli/apps/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('<int:article_id>', views.detail, name = 'detail'),
	path('<int:article_id>/leave_comment', views.leave_comment, name = 'leave_comment'),
]

bilimli/apps/questions/urls.py
from django.urls import path

from . import views
app_name = 'questions'
urlpatterns = [
	path('',views.index,name='index'),
	path('<int:question_id>', views.detail, name = 'detail'),
	path('<int:question_id>/leave_answer', views.leave_answer, name = 'leave_answer'),
]

bilimli/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # new
from django.conf.urls.static import static # new
urlpatterns = [
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
	path('', include('questions.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bilimli/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	full_name = models.CharField('Full name', max_length=50, null = True, blank = True)
	welayat = models.CharField('Which welayat', null = True, blank = True,max_length=15)
	school = models.IntegerField('School №',default = 0)
	clasy = models.IntegerField('Class',null = True, blank = True)
	rating = models.IntegerField('Rating', default = 0)
	def __unicode__(self):
		return u'Profile of user: %s' % self.user.username

bilimli/apps/articles/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.conf import settings
from django.utils import timezone

class Article(models.Model):
	title = models.CharField('Title', max_length = 100)
	text = models.TextField('Text')
	preview = models.CharField('Preview', max_length = 100)
	pub_date = models.DateTimeField('Publiced Date', auto_now_add = True)
	image = models.ImageField('Image', blank=True, null = True, upload_to = 'media')
	
	def __str__(self):
		return self.title

	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	user = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = 'Comment')
	text = models.TextField('Text')
	pub_date = models.DateTimeField('Publiced Date',auto_now_add = True)

	def __str__(self):
		return self.user.username

bilimli/apps/questions/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.conf import settings
from django.utils import timezone
class Question(models.Model):
	title = models.CharField('Title', max_length = 50)
	text = models.TextField('Text')
	preview = models.CharField('Preview', max_length = 50, blank = True, null = True)
	pub_date = models.DateTimeField('Publiced Date',auto_now_add = True)
	solved = models.BooleanField('solved', default = False)
	solver = models.ForeignKey(User,blank = True, null = True, on_delete = models.SET_NULL)
	comnum = models.IntegerField('Comment number',default = 0)
	answer1 = models.CharField('Answer', max_length = 50)
	actual = models.IntegerField('How many correct answers', default = 0)

	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 2))
	def __str__(self):
		return self.title

class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	text = models.TextField('Comment text')
	pub_date = models.DateTimeField('Comment pubdate', auto_now_add = True)
	correct = models.BooleanField('Correct', default = False)

	def __str__(self):
		return self.user.username

bilimli/apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

cities = (
	('Daşoguz','Daşoguz'),
	('Lebap','Lebap'),
	('Mary','Mary'),
	('Ahal','Ahal'),
	('Balkan','Balkan'),
)
classes = (
	('4','4'),
	('5','5'),
	('6','6'),
	('7','7'),
	('8','8'),
	('9','9'),
	('10','10'),
	('11','11'),
)
class UserRegisterForm(UserCreationForm):
	full_name = forms.CharField(max_length = 50)
	city = forms.ChoiceField(choices = cities)
	klass = forms.ChoiceField(choices = classes)
	school = forms.IntegerField()
	class Meta:
		model = User
		fields = ['username','full_name','city','school','klass','password1',]

class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ()

class ProfileEditForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('full_name','welayat','school','clasy',)

bilimli/apps/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, UserEditForm, ProfileEditForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            new_user = form.save(commit=False)
            new_user.save()
            profile = Profile.objects.create(user = new_user)
            profile.full_name = form.cleaned_data.get('full_name')
            profile.welayat = form.cleaned_data.get('city')
            profile.clasy = form.cleaned_data.get('klass')
            profile.save()
            messages.success(request, f'Account created for {username}. Now you can login!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'signup.html', {'form': form})

@login_required
def edit(request):
    top_users = Profile.objects.order_by('-rating')[:10]
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data = request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data = request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('questions:index')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        return render(request, 'accounts/edit.html', {'user_form':user_form, 'profile_form': profile_form, 'top_users':top_users})

@login_required
def profile(request, username):
    top_users = Profile.objects.order_by('-rating')[:10]
    user1 = User.objects.get(username = username)
    return render(request, 'accounts/profile.html', {'user1':user1, 'top_users':top_users})

bilimli/apps/articles/views.py
from django.shortcuts import render
from .models import Article, Comment
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from accounts.models import Profile
from django.core.paginator import Paginator

def index(request):
	latest_articles_list = Article.objects.order_by('-pub_date')
	top_users = Profile.objects.order_by('-rating')[:10]
	for a in latest_articles_list:
		a.preview = a.text[:30] + '...'
		a.save()
	paginator = Paginator(latest_articles_list, 4)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	count_pages = int(page_obj.paginator.num_pages)
	pages = [int(i) for i in range(1,count_pages+1)]
	return render(request, 'articles/list.html',{'latest_articles_list':latest_articles_list,'page_obj':page_obj, 'pages':pages, 'top_users':top_users})

def detail(request, article_id):
	a = Article.objects.get(id = article_id)
	top_users = Profile.objects.order_by('-rating')[:10]
	comment_list = a.comment_set.order_by('-pub_date')
	return render(request, 'articles/detail.html',{'a':a, 'comment_list':comment_list, 'top_users':top_users})

def leave_comment(request, article_id):
	a = Article.objects.get(id = article_id)
	a.comment_set.create(user = request.user, text = request.POST['text'])
	return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)))

bilimli/apps/questions/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Question, Answer
from accounts.models import Profile
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator

def index(request):
	questions = Question.objects.order_by('-id')
	top_users = Profile.objects.order_by('-rating')[:10]
	for question in questions:
		question.preview = question.text[:45] + '...'
		question.comnum = question.answer_set.count()
	question.save()
	paginator = Paginator(questions, 5)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	count_pages = int(page_obj.paginator.num_pages)
	pages = [int(i) for i in range(1,count_pages+1)]
	return render(request, 'questions/list.html',{'questions':questions, 'top_users':top_users, 'page_obj':page_obj, 'pages':pages})

def detail(request, question_id):
	a = Question.objects.get(id = question_id)
	top_users = Profile.objects.order_by('-rating')[:10]
	answer_list = a.answer_set.order_by('-pub_date')[:10:-1]
	for answer in a.answer_set.all():
		if answer.text == a.answer1 and a.solved == False:
			answer.correct = True
		if answer.correct and a.solved == False:
			answer.user.profile.rating += a.actual
			a.solved = True
			a.solver = answer.user 
		answer.save()
		a.comnum = a.answer_set.count()
		a.save()
		answer.user.profile.save()
	return render(request, 'questions/detail.html',{'answer_list':answer_list, 'q':a,'top_users':top_users})

def leave_answer(request, question_id):
	a = Question.objects.get(id = question_id)
	a.answer_set.create(user = request.user, text = request.POST['text'])
	return HttpResponseRedirect( reverse('questions:detail', args = (a.id,)))

bilimli/templates/questions/detail.html
{% extends 'base.html' %}

{% block title %} {{q.title}} {% endblock %}

{% block content %}


<div class="container">
	<a href="{% url 'questions:index' %}"><i class='fas fa-arrow-left' style='font-size:24px'></i></a>
<br>
	<p class="text-white">{{q.pub_date}}</p>
	<h3 class="text-white">{{q.text | linebreaks}}</h3>
	{% if q.solved %}
	<h4 style="color: #bdf564; text-transform: uppercase;">Çözüldi - {{q.solver}} tarapyndan </h4> 
	{% endif %}
	<hr class="bg-light">
	<h3 style="color: #ffc107;">Jogaplar ({{q.comnum}} sany):</h3>
	<hr class="bg-light">
	{% if answer_list %}
	{% for answer in answer_list %}
	{% if answer.correct %}
		<div class="card" style="background-color: #99c84f;">
			<div class="card-header">{{answer.user.username}}</div>
			<div class="card-body ">
		{{answer.text | linebreaks}}
			<em class="text-black"> {{answer.pub_date}} </em>
		</div>
		</div>
		<br>
		{% else %}
		<div class="card">
			<div class="card-header bg-secondary text-white">{{answer.user.username}}</div>
			<div class="card-body bg-dark">
			<p class="h6">{{answer.text | linebreaks}}</p>
			<em class="text-white"> {{answer.pub_date}} </em>
		</div>
		</div>
		<br>
		{% endif %}
	{% endfor %}
	{% else %}
	<h4>Jogaplar hali gelenak, birinji bolun! ;)</h4>
	{% endif %}
	<hr class="bg-light">
	{% if user.is_authenticated %}
	<form class="form-control bg-secondary text-white" action="{% url 'questions:leave_answer' q.id %}" method="POST">
		{% csrf_token %}
			<h4>{{user.username}}</h4>
			<textarea type="text" class="form-control bg-dark text-white" name="text" placeholder="Jogabynyz"></textarea>
			<br>
		<button type="submit" class="btn btn-warning pl-2 pr-2">Jogap gos</button>
	</form>
	{% else %}
	<p style="font-size: 24px;">Jogap yazmak ucin, sayta girin</p>
	{% endif %}
</div>
{% endblock %}

bilimli/templates/questions/list.html
{% extends 'base.html' %}

{% block title %}

	Soraglar

{% endblock %}
{% block content %}
{% for q in page_obj %}
<div class="card text-center">
  <div class="card-header text-white {% if q.solved %} bg-success {% else %} bg-secondary {% endif %}" >
    {{q.title}}
  </div>
  <div class="card-body bg-dark">
    <p class="card-text ">{{q.preview}}</p>
    <a href="{% url 'questions:detail' q.id %}" class="btn btn-warning">Read more</a>
  </div>
  <div class="card-footer bg-secondary text-white">
    {{q.pub_date}}
    {% if q.solved %}
    <p>Çözüldi - {{q.solver.username}} tarapyndan</p>
    {% endif %}
    {% if q.was_published_recently %} - <em>Taze sorag!</em>{% endif %}
  </div>
</div>
<style type="text/css">
  .page-link{
    background-color: black;
    color:white;
  }
  .page-link:hover{
    background-color: #ffc107;
    color:black;
  }
  .page-item.active .page-link {
    z-index: 3;
    background-color:  #ffc107;
    border-color:  #ffc107;
    color:black;
}
.page-item.disabled .page-link {
    color: #fff;
    pointer-events: none;
    cursor: auto;
    background-color: #40464d ;
    border-color: #dee2e6;
}
  </style>
<br>
{% endfor %}

 <ul class="pagination justify-content-center ">
  {% if page_obj.has_previous %}
   <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
   {% else %}
   <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
  {% endif %}

  {% for page in pages %}
 
   {% if page_obj.number == page %}
   <li class="page-item active"><a class="page-link" href="#">{{page}}</a></li>
   {% else %}
   <li class="page-item"><a class="page-link" href="?page={{page}}">{{page}}</a></li>
  {% endif %}
  
 {% endfor %}
 
 {% if page_obj.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
  {% else %}
  <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
  {% endif %}

 </ul> 

{% endblock %}